# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-17 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_level',
            fields=[
                ('user_id', models.IntegerField(help_text='Saves persons user_id', primary_key=True, serialize=False, unique=True)),
                ('level', models.SmallIntegerField(help_text='Saves at witch level(step) of the order user is')),
                ('date', models.DateTimeField(auto_now=True, help_text='Saves time of last message from this user')),
            ],
        ),
    ]
