# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('user_id', models.IntegerField(help_text='Saves persons user_id', max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Persons firstname and lastname', max_length=100, null=True)),
                ('phone_number', models.IntegerField(help_text='Saves persons phone number', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(help_text='Saves persons user_id', max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Persons firstname and lastname', max_length=100, null=True)),
                ('phone_number', models.IntegerField(help_text='Saves persons phone number', max_length=11, null=True)),
                ('adress', models.CharField(help_text='Persons adress', max_length=100, null=True)),
                ('contract_id', models.IntegerField(help_text='Persons contract id', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.CharField(help_text='Day and time when buyer will receive his order', max_length=100),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_level',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
