# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210423_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(help_text='Saves persons phone number', max_length=12, null=True),
        ),
    ]
