# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210423_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=models.CharField(help_text='Saves persons phone number', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Saves persons phone number', max_length=11, null=True),
        ),
    ]
