# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210423_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='first_time',
            field=models.BooleanField(default=False, help_text='Is this order first persons order or not'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Saves time of last message from this user'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.CharField(default='', help_text='Day and time when buyer will receive his order', max_length=100),
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(default='', help_text='Persons firstname and lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=models.IntegerField(default='', help_text='Saves persons phone number', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(default='', help_text='Persons adress', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_id',
            field=models.IntegerField(default=-1, help_text='Persons contract id', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', help_text='Persons firstname and lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', help_text='Saves persons phone number', max_length=11),
        ),
    ]
