# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210423_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone_number',
            field=models.CharField(default='', help_text='Saves persons phone number', max_length=11),
        ),
    ]
