# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210423_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='first_time',
            field=models.CharField(default='false', help_text='Is this order first persons order or not', max_length=5),
        ),
    ]
