# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210423_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='first_time',
            new_name='firstly_time',
        ),
    ]
