# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210423_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='callback',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_id',
            field=models.IntegerField(default=-1, help_text='Persons contract id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_level',
            name='user_id',
            field=models.IntegerField(help_text='Saves persons user_id', primary_key=True, serialize=False, unique=True),
        ),
    ]
