# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210423_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(default='', help_text='Persons adress', max_length=200),
        ),
    ]
