# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210423_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='delivery_time',
            field=models.CharField(default='', help_text='Saves date and time to delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='basket',
            name='pay_type',
            field=models.CharField(default=' ', help_text='Saves payment type, cash or card or ticket', max_length=30),
        ),
        migrations.AlterField(
            model_name='basket',
            name='first_time',
            field=models.CharField(default='false', help_text='Is this order first persons order or not', max_length=6),
        ),
    ]
