# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210424_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(help_text='Saves order unique id', primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(help_text='Saves persons user_id')),
                ('first_time', models.CharField(default='false', help_text='Is this order first persons order or not', max_length=6)),
                ('contract_id', models.IntegerField(default=-1, help_text='Persons contract id')),
                ('name', models.CharField(default='', help_text='Persons firstname and lastname', max_length=100)),
                ('phone_number', models.CharField(default='', help_text='Saves persons phone number', max_length=11)),
                ('adress', models.CharField(default='', help_text='Persons adress', max_length=200)),
                ('product', models.CharField(default='', help_text='Day and time when buyer will receive his order', max_length=30)),
                ('size', models.CharField(default='', help_text='Product size', max_length=7)),
                ('count', models.IntegerField(default=-1, help_text='Count of product')),
                ('pay_type', models.CharField(default=' ', help_text='Saves payment type, cash or card or ticket', max_length=30)),
                ('delivery_time', models.CharField(default='', help_text='Saves date and time to delivery', max_length=50)),
                ('comment', models.CharField(default=' ', help_text='Comment to the order', max_length=200)),
                ('status', models.CharField(default='In processing', help_text='Order status', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='comment',
            field=models.CharField(default=' ', help_text='Comment to the order', max_length=200),
        ),
    ]
